export function Tábla(){
    return <>
         <h2>Zöldségek</h2>
         <table>
            <thead>
                <tr>
                    <th>Sorszám</th>
                    <th>Név</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Cékla</td>   
                </tr>
                <tr>
                    <td>2</td>
                    <td>Feketegyökér</td>   
                </tr>
                <tr>
                    <td>3</td>
                    <td>Csemegekukorica</td>   
                </tr>
                <tr>
                    <td>4</td>
                    <td>Répa</td>   
                </tr>
                <tr>
                    <td>5</td>
                    <td>Görögdinnye</td>   
                </tr>
            </tbody>
         </table>
    </>
}